# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import uber_pb2 as uber__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in uber_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RideSharingStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestRide = channel.unary_unary(
                '/uber.RideSharing/RequestRide',
                request_serializer=uber__pb2.RideRequest.SerializeToString,
                response_deserializer=uber__pb2.RideResponse.FromString,
                _registered_method=True)
        self.SubscribeRides = channel.stream_stream(
                '/uber.RideSharing/SubscribeRides',
                request_serializer=uber__pb2.Driver.SerializeToString,
                response_deserializer=uber__pb2.RideRequest.FromString,
                _registered_method=True)
        self.GetRideStatus = channel.unary_unary(
                '/uber.RideSharing/GetRideStatus',
                request_serializer=uber__pb2.RiderStatusRequest.SerializeToString,
                response_deserializer=uber__pb2.RiderStatusResponse.FromString,
                _registered_method=True)
        self.SubscribeToRideUpdates = channel.unary_stream(
                '/uber.RideSharing/SubscribeToRideUpdates',
                request_serializer=uber__pb2.RiderSubscription.SerializeToString,
                response_deserializer=uber__pb2.RideStatusUpdate.FromString,
                _registered_method=True)
        self.AcceptRide = channel.unary_unary(
                '/uber.RideSharing/AcceptRide',
                request_serializer=uber__pb2.AcceptRideRequest.SerializeToString,
                response_deserializer=uber__pb2.AcceptRideResponse.FromString,
                _registered_method=True)
        self.RejectRide = channel.unary_unary(
                '/uber.RideSharing/RejectRide',
                request_serializer=uber__pb2.RejectRideRequest.SerializeToString,
                response_deserializer=uber__pb2.RejectRideResponse.FromString,
                _registered_method=True)
        self.CompleteRide = channel.unary_unary(
                '/uber.RideSharing/CompleteRide',
                request_serializer=uber__pb2.RideCompletionRequest.SerializeToString,
                response_deserializer=uber__pb2.RideCompletionResponse.FromString,
                _registered_method=True)


class RideSharingServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RequestRide(self, request, context):
        """Rider sends a ride request
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeRides(self, request_iterator, context):
        """Driver subscribes to ride requests
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRideStatus(self, request, context):
        """Rider request for Status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeToRideUpdates(self, request, context):
        """New method for ride status updates
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AcceptRide(self, request, context):
        """Driver accepts a ride
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RejectRide(self, request, context):
        """Driver rejects a ride
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteRide(self, request, context):
        """Driver completes ride
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RideSharingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestRide': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestRide,
                    request_deserializer=uber__pb2.RideRequest.FromString,
                    response_serializer=uber__pb2.RideResponse.SerializeToString,
            ),
            'SubscribeRides': grpc.stream_stream_rpc_method_handler(
                    servicer.SubscribeRides,
                    request_deserializer=uber__pb2.Driver.FromString,
                    response_serializer=uber__pb2.RideRequest.SerializeToString,
            ),
            'GetRideStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRideStatus,
                    request_deserializer=uber__pb2.RiderStatusRequest.FromString,
                    response_serializer=uber__pb2.RiderStatusResponse.SerializeToString,
            ),
            'SubscribeToRideUpdates': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeToRideUpdates,
                    request_deserializer=uber__pb2.RiderSubscription.FromString,
                    response_serializer=uber__pb2.RideStatusUpdate.SerializeToString,
            ),
            'AcceptRide': grpc.unary_unary_rpc_method_handler(
                    servicer.AcceptRide,
                    request_deserializer=uber__pb2.AcceptRideRequest.FromString,
                    response_serializer=uber__pb2.AcceptRideResponse.SerializeToString,
            ),
            'RejectRide': grpc.unary_unary_rpc_method_handler(
                    servicer.RejectRide,
                    request_deserializer=uber__pb2.RejectRideRequest.FromString,
                    response_serializer=uber__pb2.RejectRideResponse.SerializeToString,
            ),
            'CompleteRide': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteRide,
                    request_deserializer=uber__pb2.RideCompletionRequest.FromString,
                    response_serializer=uber__pb2.RideCompletionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'uber.RideSharing', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('uber.RideSharing', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RideSharing(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RequestRide(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uber.RideSharing/RequestRide',
            uber__pb2.RideRequest.SerializeToString,
            uber__pb2.RideResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeRides(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/uber.RideSharing/SubscribeRides',
            uber__pb2.Driver.SerializeToString,
            uber__pb2.RideRequest.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRideStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uber.RideSharing/GetRideStatus',
            uber__pb2.RiderStatusRequest.SerializeToString,
            uber__pb2.RiderStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeToRideUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/uber.RideSharing/SubscribeToRideUpdates',
            uber__pb2.RiderSubscription.SerializeToString,
            uber__pb2.RideStatusUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AcceptRide(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uber.RideSharing/AcceptRide',
            uber__pb2.AcceptRideRequest.SerializeToString,
            uber__pb2.AcceptRideResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RejectRide(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uber.RideSharing/RejectRide',
            uber__pb2.RejectRideRequest.SerializeToString,
            uber__pb2.RejectRideResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompleteRide(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uber.RideSharing/CompleteRide',
            uber__pb2.RideCompletionRequest.SerializeToString,
            uber__pb2.RideCompletionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
